// ---------------------------------------------------------------------------
#ifndef NVansStringsH
#define NVansStringsH
// ---------------------------------------------------------------------------

#define IDS_COPYRIGHT								1
#define IDS_COPYRIGHT_STATUS						2

#define IDS_QUESTION_CLOSE_PROGRAM					100
#define IDS_QUESTION_CLOSE_PROGRAM_CHANGED			101
#define IDS_QUESTION_SAVE_VANPROPS					102
#define IDS_QUESTION_DATA_OVERWRITE					103
#define IDS_QUESTION_DATA_NEED_SAVE					104

#define IDS_ERROR_UNKNOWN							200
#define IDS_ERROR_UNKNOWN_EXCEPTION					201
#define IDS_ERROR_LOAD_SETTINGS						202
#define IDS_ERROR_SAVE_SETTINGS						203
#define IDS_ERROR_NEED_RWNUM						204
#define IDS_ERROR_PASS_WRONG						205
#define IDS_ERROR_CHECK_PASS						206

#define IDS_ERROR_ORACLE_LOAD_TRAIN					220
#define IDS_ERROR_ORACLE_LOAD_TRAINS				221
#define IDS_ERROR_ORACLE_LOAD_TRAIN_DATETIME		222
#define IDS_ERROR_LOCAL_LOAD_VANS					230
#define IDS_ERROR_LOCAL_SAVE_VANS					231
#define IDS_ERROR_LOCAL_SAVE_VAN_PROPS				232
#define IDS_ERROR_LOCAL_LOAD_TRAINS					233

#define IDS_ERROR_AVITEK_NEED_SAVE					250

#define IDS_MSG_DATABASE_CONNECT_OK					300
#define IDS_MSG_DATABASE_CONNECT_FAIL				301
#define IDS_MSG_RWNUM_NOT_EXISTS					302
#define IDS_MSG_MATCH_NOT_FOUND						303

#define IDS_STATUS_TRAIN_LIST_COUNT					400
#define IDS_STATUS_DATA_LOAD						401
#define IDS_STATUS_DATA_SAVE						402

#define IDS_CONNECTION_MYSQL_DRIVER_0				1000
#define IDS_CONNECTION_MYSQL_DRIVER_1				1001
#define IDS_CONNECTION_ORACLE_DRIVER_0				1010
#define IDS_CONNECTION_ORACLE_DRIVER_1				1011

#define IDS_LOG_LOGIN_OK							2001
#define IDS_LOG_LOGIN_CANCEL						2002
#define IDS_LOG_OPTIONS_SAVE						2003
#define IDS_LOG_OPTIONS_CANCEL						2004

#define IDS_LOG_ERROR_EXCEPTION						2100
#define IDS_LOG_ERROR_CHECK_SETTINGS				2101
#define IDS_LOG_ERROR_LOAD_SETTINGS					2102
#define IDS_LOG_ERROR_SAVE_SETTINGS					2103
#define IDS_LOG_ERROR_PASS_WRONG					2110
#define IDS_LOG_ERROR_TERMINATED_IN_WORK_PROGRESS	2120
#define IDS_LOG_ERROR_AVITEK_NEED_SAVE				2130
#define IDS_LOG_ERROR_AVITEK_SAVE_BTN_NOT_FOUND		2131
#define IDS_LOG_ERROR_AVITEK_UPD_BTN_NOT_FOUND		2132

#define IDS_LOG_DATABASE_CONNECT					2200
#define IDS_LOG_DATABASE_CONNECT_OK					2201
#define IDS_LOG_DATABASE_CONNECT_FAIL				2202

#define IDS_LOG_ORACLE_LOAD_TRAIN_OK				2300
#define IDS_LOG_ORACLE_LOAD_TRAIN_FAIL				2301
#define IDS_LOG_ORACLE_LOAD_TRAINS_OK				2302
#define IDS_LOG_ORACLE_LOAD_TRAINS_FAIL				2303
#define IDS_LOG_ORACLE_LOAD_TRAIN_DATETIME_OK		2304
#define IDS_LOG_ORACLE_LOAD_TRAIN_DATETIME_FAIL		2305

#define IDS_LOG_LOCAL_LOAD_VANS_OK					2400
#define IDS_LOG_LOCAL_LOAD_VANS_FAIL				2401
#define IDS_LOG_LOCAL_SAVE_VANS_OK					2402
#define IDS_LOG_LOCAL_SAVE_VANS_FAIL				2403
#define IDS_LOG_LOCAL_SAVE_VAN_PROPS_OK				2404
#define IDS_LOG_LOCAL_SAVE_VAN_PROPS_FAIL			2405
#define IDS_LOG_LOCAL_LOAD_TRAINS_OK				2406
#define IDS_LOG_LOCAL_LOAD_TRAINS_FAIL				2407

#define IDS_LOG_COPY_DATA							2500
#define IDS_LOG_COPY_DATA_NOT_FOUND					2501
#define IDS_LOG_COPY_DATA_OVERWRITE_CANCEL			2502

// ---------------------------------------------------------------------------
#endif
