SELECT TO_NCHAR(RWNUM) RWNUM, NDATETIME, COUNT(*) VAN_COUNT
FROM BPTL.RP_NVANS
WHERE RWNUM IS NOT NULL AND NDATETIME>=:DATE_FROM AND NDATETIME<:DATE_TO
GROUP BY RWNUM, NDATETIME
ORDER BY NDATETIME DESC, RWNUM;