SELECT A.NUM, A.NDATETIME, TO_NCHAR(A.INVNUM) INVNUM,
	TO_NCHAR(COALESCE(B.CARGOTYPE, A.CARGOTYPE)) CARGOTYPE,
	TO_NCHAR(COALESCE(B.INVOICE_NUM, A.INVOICE_NUM)) INVOICE_NUM,
	TO_NCHAR(COALESCE(B.INVOICE_SUPPLIER, A.INVOICE_SUPPLIER)) INVOICE_SUPPLIER,
	TO_NCHAR(COALESCE(B.INVOICE_CONSIGN, A.INVOICE_CONSIGN)) INVOICE_CONSIGN,
	TO_NCHAR(COALESCE(B.DEPART_STATION, A.DEPART_STATION)) DEPART_STATION,
	TO_NCHAR(COALESCE(B.PURPOSE_STATION, A.PURPOSE_STATION)) PURPOSE_STATION,
	COALESCE(B.CARRYING, A.CARRYING) CARRYING, COALESCE(B.TARE_T, A.TARE_T) TARE_T, 
	COALESCE(B.INVOICE_NETTO, A.INVOICE_NETTO) INVOICE_NETTO,
	COALESCE(B.INVOICE_TARE, A.INVOICE_TARE) INVOICE_TARE,
	A.RWNUM, A.DATE_RECORD FROM (
		(SELECT NUM, NDATETIME, TO_NCHAR(INVNUM) INVNUM, TO_NCHAR(CARGOTYPE) CARGOTYPE,
			TO_NCHAR(INVOICE_NUM) INVOICE_NUM, TO_NCHAR(INVOICE_SUPPLIER) INVOICE_SUPPLIER, TO_NCHAR(INVOICE_CONSIGN) INVOICE_CONSIGN,
			TO_NCHAR(DEPART_STATION) DEPART_STATION, TO_NCHAR(PURPOSE_STATION) PURPOSE_STATION,
			CARRYING, TARE_T, INVOICE_NETTO, INVOICE_TARE, RWNUM, DATE_RECORD
		FROM BPTL.RP_NVANS WHERE RWNUM=:RWNUM AND NDATETIME=TO_DATE(:NDATETIME, 'YYYY-MM-DD HH24:MI:SS')) A 
		LEFT JOIN
		(SELECT NUM, NDATETIME, TO_NCHAR(INVNUM) INVNUM, TO_NCHAR(CARGOTYPE) CARGOTYPE,
			TO_NCHAR(INVOICE_NUM) INVOICE_NUM, TO_NCHAR(INVOICE_SUPPLIER) INVOICE_SUPPLIER, TO_NCHAR(INVOICE_CONSIGN) INVOICE_CONSIGN,
			TO_NCHAR(DEPART_STATION) DEPART_STATION, TO_NCHAR(PURPOSE_STATION) PURPOSE_STATION,
			CARRYING, TARE_T, INVOICE_NETTO, INVOICE_TARE, RWNUM, DATE_RECORD
		FROM BPTL.RP_NVANS) B
		ON A.INVNUM = B.INVNUM AND TRIM(B.RWNUM) LIKE CONCAT(TRIM(A.INVOICE_NUM), '-%')
)
ORDER BY NUM, DATE_RECORD;