SELECT NUM, NDATETIME, TO_NCHAR(INVNUM) INVNUM, TO_NCHAR(CARGOTYPE) CARGOTYPE,
	TO_NCHAR(INVOICE_NUM) INVOICE_NUM, TO_NCHAR(INVOICE_SUPPLIER) INVOICE_SUPPLIER, TO_NCHAR(INVOICE_CONSIGN) INVOICE_CONSIGN,
	TO_NCHAR(DEPART_STATION) DEPART_STATION, TO_NCHAR(PURPOSE_STATION) PURPOSE_STATION,
	CARRYING * 1000 AS CARRYING, TARE_T * 100 AS TARE_T, INVOICE_NETTO, INVOICE_TARE * 100 AS INVOICE_TARE, RWNUM, DATE_RECORD
FROM BPTL.RP_NVANS
WHERE RWNUM=:RWNUM AND NDATETIME=TO_DATE(:NDATETIME, 'YYYY-MM-DD HH24:MI:SS')
ORDER BY NUM, DATE_RECORD;